### ISSUE TITLE
Typo? ESL = EML?

### ISSUE THREAD

**Issue by jesseengel** [ajbrock/SMASH#1]
Is this line a typo?

https://github.com/ajbrock/SMASH/blob/72e26ac761fb3b9c815cd5c0137fd54f7b310029/layers.py#L54

It seems to me that the EML should multiply right?

**Comment by ajbrock** [comment]
Yep, this is a typo. Fortunately I don't use that particular little wrapper anywhere, or things might have gone really wrong! Thanks for pointing it out--fixed.

**Comment by jesseengel** [comment]
No problem, glad it didn't hurt anything :).
